// Database-first column mapping. SQL migrations own foreign keys, indexes and triggers.
// Never use schema push to replace the reviewed migrations.
import { pgTable, uuid, text, integer, smallint, bigint, numeric, timestamp, boolean, jsonb, primaryKey } from "drizzle-orm/pg-core";

export const execution_runs = pgTable("execution_runs", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  workspace_id: uuid("workspace_id").notNull(),
  data_product_id: uuid("data_product_id").notNull(),
  data_product_version_id: uuid("data_product_version_id").notNull(),
  deployment_id: uuid("deployment_id"),
  refresh_schedule_id: uuid("refresh_schedule_id"),
  requested_by_user_id: uuid("requested_by_user_id"),
  run_type: text("run_type").notNull(),
  trigger_type: text("trigger_type").notNull(),
  idempotency_key: text("idempotency_key").notNull(),
  spec_hash: text("spec_hash").notNull(),
  runtime_version: text("runtime_version").notNull(),
  operator_registry_hash: text("operator_registry_hash").notNull(),
  adapter_versions_json: jsonb("adapter_versions_json").notNull(),
  status: text("status").notNull(),
  failure_code: text("failure_code"),
  failure_message: text("failure_message"),
  queued_at: timestamp("queued_at", { withTimezone: true, mode: "date" }).notNull(),
  started_at: timestamp("started_at", { withTimezone: true, mode: "date" }),
  finished_at: timestamp("finished_at", { withTimezone: true, mode: "date" }),
  metrics_json: jsonb("metrics_json"),
});

export const run_attempts = pgTable("run_attempts", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  execution_run_id: uuid("execution_run_id").notNull(),
  attempt_no: integer("attempt_no").notNull(),
  queue_provider: text("queue_provider").notNull(),
  queue_job_id: text("queue_job_id").notNull(),
  worker_instance_id: text("worker_instance_id"),
  status: text("status").notNull(),
  started_at: timestamp("started_at", { withTimezone: true, mode: "date" }),
  heartbeat_at: timestamp("heartbeat_at", { withTimezone: true, mode: "date" }),
  finished_at: timestamp("finished_at", { withTimezone: true, mode: "date" }),
  error_code: text("error_code"),
  error_message: text("error_message"),
});

export const node_runs = pgTable("node_runs", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  run_attempt_id: uuid("run_attempt_id").notNull(),
  node_id: text("node_id").notNull(),
  operator_type: text("operator_type").notNull(),
  operator_version: text("operator_version").notNull(),
  status: text("status").notNull(),
  started_at: timestamp("started_at", { withTimezone: true, mode: "date" }),
  finished_at: timestamp("finished_at", { withTimezone: true, mode: "date" }),
  metrics_json: jsonb("metrics_json"),
  error_code: text("error_code"),
  error_message: text("error_message"),
});

export const node_run_artifacts = pgTable("node_run_artifacts", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  node_run_id: uuid("node_run_id").notNull(),
  direction: text("direction").notNull(),
  port_name: text("port_name").notNull(),
  ordinal: integer("ordinal").notNull().default(0),
  artifact_id: uuid("artifact_id").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
});

export const artifacts = pgTable("artifacts", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  workspace_id: uuid("workspace_id").notNull(),
  execution_run_id: uuid("execution_run_id").notNull(),
  artifact_kind: text("artifact_kind").notNull(),
  storage_kind: text("storage_kind").notNull(),
  payload_json: jsonb("payload_json"),
  object_uri: text("object_uri"),
  schema_json: jsonb("schema_json"),
  content_hash: text("content_hash").notNull(),
  row_count: bigint("row_count", { mode: "bigint" }),
  byte_count: bigint("byte_count", { mode: "bigint" }).notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  expires_at: timestamp("expires_at", { withTimezone: true, mode: "date" }),
});

export const source_requests = pgTable("source_requests", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  workspace_id: uuid("workspace_id").notNull(),
  execution_run_id: uuid("execution_run_id").notNull(),
  node_run_id: uuid("node_run_id").notNull(),
  source_snapshot_id: uuid("source_snapshot_id").notNull(),
  request_no: integer("request_no").notNull(),
  access_mode: text("access_mode").notNull(),
  provider_credential_id: uuid("provider_credential_id"),
  spending_policy_id: uuid("spending_policy_id"),
  credential_secret_version: text("credential_secret_version"),
  credential_fingerprint: text("credential_fingerprint"),
  gateway_environment: text("gateway_environment").notNull(),
  operation_name: text("operation_name"),
  query_text: text("query_text").notNull(),
  query_hash: text("query_hash").notNull(),
  variables_json: jsonb("variables_json").notNull(),
  variables_hash: text("variables_hash").notNull(),
  pagination_cursor_json: jsonb("pagination_cursor_json"),
  requested_block_ref: text("requested_block_ref"),
  budget_reservation_id: uuid("budget_reservation_id"),
  payment_intent_id: uuid("payment_intent_id"),
  response_artifact_id: uuid("response_artifact_id"),
  response_manifest_ipfs_cid: text("response_manifest_ipfs_cid"),
  indexed_block_ref: text("indexed_block_ref"),
  indexed_block_timestamp: timestamp("indexed_block_timestamp", { withTimezone: true, mode: "date" }),
  has_indexing_errors: boolean("has_indexing_errors"),
  graphql_errors_json: jsonb("graphql_errors_json"),
  status: text("status").notNull(),
  requested_at: timestamp("requested_at", { withTimezone: true, mode: "date" }),
  completed_at: timestamp("completed_at", { withTimezone: true, mode: "date" }),
  error_code: text("error_code"),
  node_id: text("node_id").notNull(),
  request_kind: text("request_kind").notNull(),
  logical_request_key: text("logical_request_key").notNull(),
});

export const source_http_attempts = pgTable("source_http_attempts", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  source_request_id: uuid("source_request_id").notNull(),
  attempt_no: integer("attempt_no").notNull(),
  request_fingerprint: text("request_fingerprint").notNull(),
  has_payment_authorization: boolean("has_payment_authorization").notNull(),
  payment_authorization_hash: text("payment_authorization_hash"),
  payment_requirement_hash: text("payment_requirement_hash"),
  provider_request_id: text("provider_request_id"),
  http_status: integer("http_status"),
  sanitized_response_metadata_json: jsonb("sanitized_response_metadata_json"),
  status: text("status").notNull(),
  sent_at: timestamp("sent_at", { withTimezone: true, mode: "date" }).notNull(),
  completed_at: timestamp("completed_at", { withTimezone: true, mode: "date" }),
  error_code: text("error_code"),
  node_run_id: uuid("node_run_id").notNull(),
});

export const materializations = pgTable("materializations", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  workspace_id: uuid("workspace_id").notNull(),
  data_product_id: uuid("data_product_id").notNull(),
  data_product_version_id: uuid("data_product_version_id").notNull(),
  execution_run_id: uuid("execution_run_id").notNull(),
  artifact_id: uuid("artifact_id").notNull(),
  status: text("status").notNull(),
  source_freshness_at: timestamp("source_freshness_at", { withTimezone: true, mode: "date" }).notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  expires_at: timestamp("expires_at", { withTimezone: true, mode: "date" }),
});
