// Database-first column mapping. SQL migrations own foreign keys, indexes and triggers.
// Never use schema push to replace the reviewed migrations.
import { pgTable, uuid, text, integer, smallint, bigint, numeric, timestamp, boolean, jsonb, primaryKey } from "drizzle-orm/pg-core";

export const payment_intents = pgTable("payment_intents", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  workspace_id: uuid("workspace_id").notNull(),
  data_product_id: uuid("data_product_id"),
  kind: text("kind").notNull(),
  network_id: uuid("network_id").notNull(),
  asset_id: uuid("asset_id").notNull(),
  amount_atomic: numeric("amount_atomic", { precision: 78, scale: 0 }).notNull(),
  payer_wallet_address_id: uuid("payer_wallet_address_id"),
  payer_address: text("payer_address"),
  recipient_wallet_address_id: uuid("recipient_wallet_address_id"),
  recipient_address: text("recipient_address").notNull(),
  facilitator: text("facilitator").notNull(),
  payment_protocol: text("payment_protocol").notNull(),
  payment_protocol_version: text("payment_protocol_version"),
  payment_scheme: text("payment_scheme"),
  network_fee_payer_address: text("network_fee_payer_address"),
  max_timeout_seconds: integer("max_timeout_seconds"),
  resource_ref: text("resource_ref"),
  requirement_json: jsonb("requirement_json"),
  requirement_hash: text("requirement_hash"),
  selected_requirement_json: jsonb("selected_requirement_json"),
  idempotency_key: text("idempotency_key").notNull(),
  status: text("status").notNull(),
  expires_at: timestamp("expires_at", { withTimezone: true, mode: "date" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
});

export const payment_attempts = pgTable("payment_attempts", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  payment_intent_id: uuid("payment_intent_id").notNull(),
  attempt_no: integer("attempt_no").notNull(),
  network_id: uuid("network_id").notNull(),
  provider: text("provider").notNull(),
  provider_operation: text("provider_operation"),
  provider_idempotency_key: text("provider_idempotency_key"),
  provider_idempotency_expires_at: timestamp("provider_idempotency_expires_at", { withTimezone: true, mode: "date" }),
  request_fingerprint: text("request_fingerprint"),
  provider_request_id: text("provider_request_id"),
  provider_reference_id: text("provider_reference_id"),
  authorization_hash: text("authorization_hash"),
  authorization_expires_at: timestamp("authorization_expires_at", { withTimezone: true, mode: "date" }),
  provider_transaction_ref: text("provider_transaction_ref"),
  status: text("status").notNull(),
  sanitized_result_json: jsonb("sanitized_result_json"),
  requested_at: timestamp("requested_at", { withTimezone: true, mode: "date" }).notNull(),
  submitted_at: timestamp("submitted_at", { withTimezone: true, mode: "date" }),
  settled_at: timestamp("settled_at", { withTimezone: true, mode: "date" }),
  error_code: text("error_code"),
});

export const payment_settlements = pgTable("payment_settlements", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  payment_intent_id: uuid("payment_intent_id").notNull(),
  payment_attempt_id: uuid("payment_attempt_id").notNull(),
  network_id: uuid("network_id").notNull(),
  asset_id: uuid("asset_id").notNull(),
  provider: text("provider").notNull(),
  provider_transaction_ref: text("provider_transaction_ref"),
  network_transaction_id: text("network_transaction_id"),
  network_transaction_hash: text("network_transaction_hash"),
  consensus_timestamp: text("consensus_timestamp"),
  payer_address: text("payer_address"),
  fee_payer_address: text("fee_payer_address"),
  recipient_address: text("recipient_address").notNull(),
  amount_atomic: numeric("amount_atomic", { precision: 78, scale: 0 }).notNull(),
  result_code: text("result_code"),
  evidence_sources_json: jsonb("evidence_sources_json").notNull(),
  evidence_json: jsonb("evidence_json"),
  evidence_hash: text("evidence_hash"),
  status: text("status").notNull(),
  reported_at: timestamp("reported_at", { withTimezone: true, mode: "date" }).notNull(),
  confirmed_at: timestamp("confirmed_at", { withTimezone: true, mode: "date" }),
});

export const payment_allocations = pgTable("payment_allocations", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  payment_intent_id: uuid("payment_intent_id").notNull(),
  allocation_type: text("allocation_type").notNull(),
  beneficiary_wallet_address_id: uuid("beneficiary_wallet_address_id"),
  beneficiary_ref: text("beneficiary_ref"),
  amount_atomic: numeric("amount_atomic", { precision: 78, scale: 0 }).notNull(),
  status: text("status").notNull(),
  settlement_payment_intent_id: uuid("settlement_payment_intent_id"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  confirmed_at: timestamp("confirmed_at", { withTimezone: true, mode: "date" }),
});

export const financial_ledger_entries = pgTable("financial_ledger_entries", {
  id: uuid("id").notNull().primaryKey().defaultRandom(),
  workspace_id: uuid("workspace_id").notNull(),
  data_product_id: uuid("data_product_id"),
  payment_intent_id: uuid("payment_intent_id").notNull(),
  payment_allocation_id: uuid("payment_allocation_id"),
  wallet_address_id: uuid("wallet_address_id"),
  entry_type: text("entry_type").notNull(),
  accounting_view: text("accounting_view").notNull(),
  direction: text("direction").notNull(),
  network_id: uuid("network_id").notNull(),
  asset_id: uuid("asset_id").notNull(),
  amount_atomic: numeric("amount_atomic", { precision: 78, scale: 0 }).notNull(),
  recognition_status: text("recognition_status").notNull(),
  reverses_entry_id: uuid("reverses_entry_id"),
  source_key: text("source_key").notNull(),
  occurred_at: timestamp("occurred_at", { withTimezone: true, mode: "date" }).notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
});
