-- Data model 1.4: payments. Foreign keys follow after all cyclic targets exist.

CREATE TABLE "payment_intents" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "workspace_id" uuid NOT NULL,
  "data_product_id" uuid,
  "kind" text NOT NULL CHECK ("kind" IN ('top_up', 'graph_purchase', 'api_sale', 'fee_settlement', 'refund')),
  "network_id" uuid NOT NULL,
  "asset_id" uuid NOT NULL,
  "amount_atomic" numeric(78,0) NOT NULL CHECK ("amount_atomic" >= 0 AND "amount_atomic" NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)),
  "payer_wallet_address_id" uuid,
  "payer_address" text,
  "recipient_wallet_address_id" uuid,
  "recipient_address" text NOT NULL,
  "facilitator" text NOT NULL CHECK ("facilitator" IN ('graph_x402', 'blocky402', 'direct_chain_observation')),
  "payment_protocol" text NOT NULL CHECK ("payment_protocol" IN ('x402', 'direct')),
  "payment_protocol_version" text,
  "payment_scheme" text,
  "network_fee_payer_address" text,
  "max_timeout_seconds" integer CHECK ("max_timeout_seconds" >= 0),
  "resource_ref" text,
  "requirement_json" jsonb,
  "requirement_hash" text,
  "selected_requirement_json" jsonb,
  "idempotency_key" text NOT NULL,
  "status" text NOT NULL CHECK ("status" IN ('created', 'authorization_required', 'submitted', 'confirmed', 'failed', 'uncertain', 'reversed', 'expired')),
  "expires_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE "payment_attempts" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "payment_intent_id" uuid NOT NULL,
  "attempt_no" integer NOT NULL CHECK ("attempt_no" >= 0 AND "attempt_no" > 0),
  "network_id" uuid NOT NULL,
  "provider" text NOT NULL,
  "provider_operation" text,
  "provider_idempotency_key" text,
  "provider_idempotency_expires_at" timestamptz,
  "request_fingerprint" text,
  "provider_request_id" text,
  "provider_reference_id" text,
  "authorization_hash" text,
  "authorization_expires_at" timestamptz,
  "provider_transaction_ref" text,
  "status" text NOT NULL CHECK ("status" IN ('requested', 'submitted', 'confirmed', 'failed', 'uncertain')),
  "sanitized_result_json" jsonb,
  "requested_at" timestamptz NOT NULL,
  "submitted_at" timestamptz,
  "settled_at" timestamptz,
  "error_code" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "payment_settlements" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "payment_intent_id" uuid NOT NULL,
  "payment_attempt_id" uuid NOT NULL,
  "network_id" uuid NOT NULL,
  "asset_id" uuid NOT NULL,
  "provider" text NOT NULL,
  "provider_transaction_ref" text,
  "network_transaction_id" text,
  "network_transaction_hash" text,
  "consensus_timestamp" text,
  "payer_address" text,
  "fee_payer_address" text,
  "recipient_address" text NOT NULL,
  "amount_atomic" numeric(78,0) NOT NULL CHECK ("amount_atomic" >= 0 AND "amount_atomic" NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)),
  "result_code" text,
  "evidence_sources_json" jsonb NOT NULL,
  "evidence_json" jsonb,
  "evidence_hash" text,
  "status" text NOT NULL CHECK ("status" IN ('reported', 'confirmed', 'mismatched', 'failed')),
  "reported_at" timestamptz NOT NULL,
  "confirmed_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE "payment_allocations" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "payment_intent_id" uuid NOT NULL,
  "allocation_type" text NOT NULL CHECK ("allocation_type" IN ('gross_sale', 'creator_proceeds', 'platform_fee', 'provider_fee', 'network_fee', 'graph_expense', 'refund')),
  "beneficiary_wallet_address_id" uuid,
  "beneficiary_ref" text,
  "amount_atomic" numeric(78,0) NOT NULL CHECK ("amount_atomic" >= 0 AND "amount_atomic" NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)),
  "status" text NOT NULL CHECK ("status" IN ('planned', 'confirmed', 'failed', 'not_applicable')),
  "settlement_payment_intent_id" uuid,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "confirmed_at" timestamptz,
  PRIMARY KEY ("id")
);

CREATE TABLE "financial_ledger_entries" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "workspace_id" uuid NOT NULL,
  "data_product_id" uuid,
  "payment_intent_id" uuid NOT NULL,
  "payment_allocation_id" uuid,
  "wallet_address_id" uuid,
  "entry_type" text NOT NULL CHECK ("entry_type" IN ('top_up', 'graph_expense', 'gross_sale', 'creator_proceeds', 'provider_fee', 'platform_fee', 'refund')),
  "accounting_view" text NOT NULL CHECK ("accounting_view" IN ('cash_movement', 'economic_allocation')),
  "direction" text NOT NULL CHECK ("direction" IN ('inflow', 'outflow', 'memo')),
  "network_id" uuid NOT NULL,
  "asset_id" uuid NOT NULL,
  "amount_atomic" numeric(78,0) NOT NULL CHECK ("amount_atomic" >= 0 AND "amount_atomic" NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)),
  "recognition_status" text NOT NULL CHECK ("recognition_status" IN ('confirmed', 'reversed')),
  "reverses_entry_id" uuid,
  "source_key" text NOT NULL,
  "occurred_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
