-- Structural invariants and query indexes. Numerical operating caps are not seeded.
ALTER TABLE "users" ADD CONSTRAINT uq_001 UNIQUE ("auth_provider", "auth_subject");
ALTER TABLE "workspaces" ADD CONSTRAINT uq_002 UNIQUE ("slug");
ALTER TABLE "workspace_members" ADD CONSTRAINT uq_003 UNIQUE ("workspace_id", "user_id");
ALTER TABLE "networks" ADD CONSTRAINT uq_004 UNIQUE ("namespace", "reference");
ALTER TABLE "assets" ADD CONSTRAINT uq_005 UNIQUE ("network_id", "standard", "asset_identifier");
ALTER TABLE "account_wallets" ADD CONSTRAINT uq_006 UNIQUE ("provider", "provider_wallet_id");
ALTER TABLE "account_wallets" ADD CONSTRAINT uq_007 UNIQUE ("provider", "provider_external_id");
ALTER TABLE "wallet_addresses" ADD CONSTRAINT uq_008 UNIQUE ("network_id", "address_kind", "normalized_address");
ALTER TABLE "wallet_policies" ADD CONSTRAINT uq_009 UNIQUE ("provider", "provider_policy_id", "revision_no");
ALTER TABLE "wallet_policies" ADD CONSTRAINT uq_010 UNIQUE ("provider", "provider_policy_id", "definition_hash");
ALTER TABLE "wallet_signer_grants" ADD CONSTRAINT uq_011 UNIQUE ("account_wallet_id", "provider", "provider_signer_id");
ALTER TABLE "budget_reservations" ADD CONSTRAINT uq_012 UNIQUE ("spending_policy_id", "idempotency_key");
ALTER TABLE "agent_messages" ADD CONSTRAINT uq_013 UNIQUE ("agent_session_id", "sequence_no");
ALTER TABLE "provider_credentials" ADD CONSTRAINT uq_014 UNIQUE ("workspace_id", "provider", "label");
ALTER TABLE "provider_credentials" ADD CONSTRAINT uq_015 UNIQUE ("workspace_id", "provider", "credential_fingerprint");
ALTER TABLE "source_snapshots" ADD CONSTRAINT uq_016 UNIQUE ("workspace_id", "provider", "gateway_target_type", "gateway_target_id", "schema_hash");
ALTER TABLE "data_products" ADD CONSTRAINT uq_017 UNIQUE ("workspace_id", "slug");
ALTER TABLE "data_product_versions" ADD CONSTRAINT uq_018 UNIQUE ("data_product_id", "version_no");
ALTER TABLE "deployments" ADD CONSTRAINT uq_019 UNIQUE ("data_product_id", "environment");
ALTER TABLE "deployments" ADD CONSTRAINT uq_020 UNIQUE ("environment", "endpoint_slug");
ALTER TABLE "publication_versions" ADD CONSTRAINT uq_021 UNIQUE ("deployment_id", "revision_no");
ALTER TABLE "api_credentials" ADD CONSTRAINT uq_022 UNIQUE ("key_hash");
ALTER TABLE "execution_runs" ADD CONSTRAINT uq_023 UNIQUE ("workspace_id", "idempotency_key");
ALTER TABLE "run_attempts" ADD CONSTRAINT uq_024 UNIQUE ("execution_run_id", "attempt_no");
ALTER TABLE "run_attempts" ADD CONSTRAINT uq_025 UNIQUE ("queue_provider", "queue_job_id");
ALTER TABLE "node_runs" ADD CONSTRAINT uq_026 UNIQUE ("run_attempt_id", "node_id");
ALTER TABLE "node_run_artifacts" ADD CONSTRAINT uq_027 UNIQUE ("node_run_id", "direction", "port_name", "ordinal");
ALTER TABLE "source_requests" ADD CONSTRAINT uq_028 UNIQUE ("execution_run_id", "node_id", "request_no");
ALTER TABLE "source_requests" ADD CONSTRAINT uq_029 UNIQUE ("execution_run_id", "node_id", "logical_request_key");
ALTER TABLE "source_http_attempts" ADD CONSTRAINT uq_030 UNIQUE ("source_request_id", "attempt_no");
ALTER TABLE "source_http_attempts" ADD CONSTRAINT uq_031 UNIQUE ("payment_authorization_hash");
ALTER TABLE "materializations" ADD CONSTRAINT uq_032 UNIQUE ("execution_run_id");
ALTER TABLE "trace_events" ADD CONSTRAINT uq_033 UNIQUE ("trace_stream_id", "sequence_no");
ALTER TABLE "api_access_requests" ADD CONSTRAINT uq_034 UNIQUE ("deployment_id", "correlation_id");
ALTER TABLE "api_access_requests" ADD CONSTRAINT uq_035 UNIQUE ("recovery_capability_hash");
ALTER TABLE "api_http_attempts" ADD CONSTRAINT uq_036 UNIQUE ("api_access_request_id", "attempt_no");
ALTER TABLE "payment_intents" ADD CONSTRAINT uq_037 UNIQUE ("workspace_id", "idempotency_key");
ALTER TABLE "payment_attempts" ADD CONSTRAINT uq_038 UNIQUE ("payment_intent_id", "attempt_no");
ALTER TABLE "payment_attempts" ADD CONSTRAINT uq_039 UNIQUE ("provider", "provider_request_id");
ALTER TABLE "payment_attempts" ADD CONSTRAINT uq_040 UNIQUE ("provider", "provider_reference_id");
ALTER TABLE "payment_attempts" ADD CONSTRAINT uq_041 UNIQUE ("provider", "provider_idempotency_key");
ALTER TABLE "payment_settlements" ADD CONSTRAINT uq_042 UNIQUE ("provider", "provider_transaction_ref");
ALTER TABLE "payment_settlements" ADD CONSTRAINT uq_043 UNIQUE ("network_id", "network_transaction_id");
ALTER TABLE "payment_settlements" ADD CONSTRAINT uq_044 UNIQUE ("network_id", "network_transaction_hash");
ALTER TABLE "financial_ledger_entries" ADD CONSTRAINT uq_045 UNIQUE ("workspace_id", "source_key");
ALTER TABLE "command_dispatches" ADD CONSTRAINT uq_046 UNIQUE ("deduplication_key");
ALTER TABLE "planning_calls" ADD CONSTRAINT uq_047 UNIQUE ("control_command_id", "logical_call_key", "attempt_no");
ALTER TABLE "compilation_records" ADD CONSTRAINT uq_048 UNIQUE ("proposal_message_id");
ALTER TABLE "compilation_records" ADD CONSTRAINT uq_049 UNIQUE ("data_product_version_id");
ALTER TABLE control_commands ADD CONSTRAINT commands_replay_scope UNIQUE NULLS NOT DISTINCT (actor_user_id, workspace_id, operation, idempotency_key);
CREATE UNIQUE INDEX uq_partial_050 ON "wallet_asset_capabilities" ("wallet_address_id", "asset_id") WHERE status = 'active';
CREATE UNIQUE INDEX uq_partial_051 ON "wallet_policies" ("provider", "provider_policy_id") WHERE status = 'active';
CREATE UNIQUE INDEX uq_partial_052 ON "workspace_members" ("workspace_id") WHERE role = 'owner' AND status = 'active';
CREATE UNIQUE INDEX uq_partial_053 ON "refresh_schedules" ("deployment_id") WHERE status = 'active';
CREATE UNIQUE INDEX uq_partial_054 ON "payment_settlements" ("payment_intent_id") WHERE status = 'confirmed';
CREATE UNIQUE INDEX uq_partial_055 ON "api_access_requests" ("deployment_id", "api_credential_id", "idempotency_key") WHERE api_credential_id IS NOT NULL AND idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX uq_partial_056 ON "api_access_requests" ("deployment_id", "caller_user_id", "idempotency_key") WHERE caller_user_id IS NOT NULL AND api_credential_id IS NULL AND idempotency_key IS NOT NULL;
CREATE INDEX ix_001 ON "workspaces" ("owner_user_id");
CREATE INDEX ix_002 ON "workspace_members" ("workspace_id");
CREATE INDEX ix_003 ON "workspace_members" ("user_id");
CREATE INDEX ix_004 ON "assets" ("network_id");
CREATE INDEX ix_005 ON "account_wallets" ("workspace_id");
CREATE INDEX ix_006 ON "account_wallets" ("owner_user_id");
CREATE INDEX ix_007 ON "wallet_addresses" ("account_wallet_id");
CREATE INDEX ix_008 ON "wallet_addresses" ("network_id");
CREATE INDEX ix_009 ON "wallet_asset_capabilities" ("wallet_address_id");
CREATE INDEX ix_010 ON "wallet_asset_capabilities" ("asset_id");
CREATE INDEX ix_011 ON "wallet_policies" ("workspace_id");
CREATE INDEX ix_012 ON "wallet_signer_grants" ("workspace_id");
CREATE INDEX ix_013 ON "wallet_signer_grants" ("account_wallet_id");
CREATE INDEX ix_014 ON "wallet_signer_grants" ("wallet_policy_id");
CREATE INDEX ix_015 ON "wallet_signer_grants" ("granted_by_user_id");
CREATE INDEX ix_016 ON "spending_policies" ("workspace_id");
CREATE INDEX ix_017 ON "spending_policies" ("wallet_signer_grant_id");
CREATE INDEX ix_018 ON "spending_policies" ("network_id");
CREATE INDEX ix_019 ON "spending_policies" ("asset_id");
CREATE INDEX ix_020 ON "spending_policies" ("created_by_user_id");
CREATE INDEX ix_021 ON "budget_reservations" ("spending_policy_id");
CREATE INDEX ix_022 ON "budget_reservations" ("execution_run_id");
CREATE INDEX ix_023 ON "budget_reservations" ("consumed_payment_intent_id");
CREATE INDEX ix_024 ON "wallet_balance_snapshots" ("wallet_address_id");
CREATE INDEX ix_025 ON "wallet_balance_snapshots" ("asset_id");
CREATE INDEX ix_026 ON "agent_sessions" ("workspace_id");
CREATE INDEX ix_027 ON "agent_sessions" ("created_by_user_id");
CREATE INDEX ix_028 ON "agent_sessions" ("data_product_id");
CREATE INDEX ix_029 ON "agent_messages" ("agent_session_id");
CREATE INDEX ix_030 ON "provider_credentials" ("workspace_id");
CREATE INDEX ix_031 ON "provider_credentials" ("created_by_user_id");
CREATE INDEX ix_032 ON "source_snapshots" ("workspace_id");
CREATE INDEX ix_033 ON "data_products" ("workspace_id");
CREATE INDEX ix_034 ON "data_products" ("creator_user_id");
CREATE INDEX ix_035 ON "data_products" ("account_wallet_id");
CREATE INDEX ix_036 ON "data_product_versions" ("data_product_id");
CREATE INDEX ix_037 ON "data_product_versions" ("parent_version_id");
CREATE INDEX ix_038 ON "data_product_versions" ("created_by_user_id");
CREATE INDEX ix_039 ON "data_product_versions" ("agent_session_id");
CREATE INDEX ix_040 ON "data_product_version_sources" ("source_snapshot_id");
CREATE INDEX ix_041 ON "data_product_version_sources" ("provider_credential_id");
CREATE INDEX ix_042 ON "data_product_version_sources" ("spending_policy_id");
CREATE INDEX ix_043 ON "product_version_layouts" ("updated_by_user_id");
CREATE INDEX ix_044 ON "deployments" ("workspace_id");
CREATE INDEX ix_045 ON "deployments" ("data_product_id");
CREATE INDEX ix_046 ON "deployments" ("active_version_id");
CREATE INDEX ix_047 ON "deployments" ("active_materialization_id");
CREATE INDEX ix_048 ON "deployments" ("active_publication_version_id");
CREATE INDEX ix_049 ON "publication_versions" ("deployment_id");
CREATE INDEX ix_050 ON "publication_versions" ("network_id");
CREATE INDEX ix_051 ON "publication_versions" ("asset_id");
CREATE INDEX ix_052 ON "publication_versions" ("recipient_wallet_address_id");
CREATE INDEX ix_053 ON "publication_versions" ("accepted_by_user_id");
CREATE INDEX ix_054 ON "api_credentials" ("workspace_id");
CREATE INDEX ix_055 ON "api_credentials" ("deployment_id");
CREATE INDEX ix_056 ON "api_credentials" ("created_by_user_id");
CREATE INDEX ix_057 ON "refresh_schedules" ("workspace_id");
CREATE INDEX ix_058 ON "refresh_schedules" ("deployment_id");
CREATE INDEX ix_059 ON "execution_runs" ("workspace_id");
CREATE INDEX ix_060 ON "execution_runs" ("data_product_id");
CREATE INDEX ix_061 ON "execution_runs" ("data_product_version_id");
CREATE INDEX ix_062 ON "execution_runs" ("deployment_id");
CREATE INDEX ix_063 ON "execution_runs" ("refresh_schedule_id");
CREATE INDEX ix_064 ON "execution_runs" ("requested_by_user_id");
CREATE INDEX ix_065 ON "run_attempts" ("execution_run_id");
CREATE INDEX ix_066 ON "node_runs" ("run_attempt_id");
CREATE INDEX ix_067 ON "node_run_artifacts" ("node_run_id");
CREATE INDEX ix_068 ON "node_run_artifacts" ("artifact_id");
CREATE INDEX ix_069 ON "artifacts" ("workspace_id");
CREATE INDEX ix_070 ON "artifacts" ("execution_run_id");
CREATE INDEX ix_071 ON "source_requests" ("workspace_id");
CREATE INDEX ix_072 ON "source_requests" ("execution_run_id");
CREATE INDEX ix_073 ON "source_requests" ("node_run_id");
CREATE INDEX ix_074 ON "source_requests" ("source_snapshot_id");
CREATE INDEX ix_075 ON "source_requests" ("provider_credential_id");
CREATE INDEX ix_076 ON "source_requests" ("spending_policy_id");
CREATE INDEX ix_077 ON "source_requests" ("budget_reservation_id");
CREATE INDEX ix_078 ON "source_requests" ("payment_intent_id");
CREATE INDEX ix_079 ON "source_requests" ("response_artifact_id");
CREATE INDEX ix_080 ON "source_http_attempts" ("source_request_id");
CREATE INDEX ix_081 ON "source_http_attempts" ("node_run_id");
CREATE INDEX ix_082 ON "materializations" ("workspace_id");
CREATE INDEX ix_083 ON "materializations" ("data_product_id");
CREATE INDEX ix_084 ON "materializations" ("data_product_version_id");
CREATE INDEX ix_085 ON "materializations" ("execution_run_id");
CREATE INDEX ix_086 ON "materializations" ("artifact_id");
CREATE INDEX ix_087 ON "trace_streams" ("workspace_id");
CREATE INDEX ix_088 ON "trace_streams" ("data_product_id");
CREATE INDEX ix_089 ON "trace_streams" ("data_product_version_id");
CREATE INDEX ix_090 ON "trace_streams" ("agent_session_id");
CREATE INDEX ix_091 ON "trace_streams" ("execution_run_id");
CREATE INDEX ix_092 ON "trace_events" ("trace_stream_id");
CREATE INDEX ix_093 ON "api_access_requests" ("workspace_id");
CREATE INDEX ix_094 ON "api_access_requests" ("deployment_id");
CREATE INDEX ix_095 ON "api_access_requests" ("data_product_version_id");
CREATE INDEX ix_096 ON "api_access_requests" ("publication_version_id");
CREATE INDEX ix_097 ON "api_access_requests" ("materialization_id");
CREATE INDEX ix_098 ON "api_access_requests" ("api_credential_id");
CREATE INDEX ix_099 ON "api_access_requests" ("caller_user_id");
CREATE INDEX ix_100 ON "api_access_requests" ("payment_intent_id");
CREATE INDEX ix_101 ON "api_http_attempts" ("api_access_request_id");
CREATE INDEX ix_102 ON "usage_events" ("workspace_id");
CREATE INDEX ix_103 ON "usage_events" ("data_product_id");
CREATE INDEX ix_104 ON "usage_events" ("execution_run_id");
CREATE INDEX ix_105 ON "usage_events" ("source_request_id");
CREATE INDEX ix_106 ON "usage_events" ("api_access_request_id");
CREATE INDEX ix_107 ON "payment_intents" ("workspace_id");
CREATE INDEX ix_108 ON "payment_intents" ("data_product_id");
CREATE INDEX ix_109 ON "payment_intents" ("network_id");
CREATE INDEX ix_110 ON "payment_intents" ("asset_id");
CREATE INDEX ix_111 ON "payment_intents" ("payer_wallet_address_id");
CREATE INDEX ix_112 ON "payment_intents" ("recipient_wallet_address_id");
CREATE INDEX ix_113 ON "payment_attempts" ("payment_intent_id");
CREATE INDEX ix_114 ON "payment_attempts" ("network_id");
CREATE INDEX ix_115 ON "payment_settlements" ("payment_intent_id");
CREATE INDEX ix_116 ON "payment_settlements" ("payment_attempt_id");
CREATE INDEX ix_117 ON "payment_settlements" ("network_id");
CREATE INDEX ix_118 ON "payment_settlements" ("asset_id");
CREATE INDEX ix_119 ON "payment_allocations" ("payment_intent_id");
CREATE INDEX ix_120 ON "payment_allocations" ("beneficiary_wallet_address_id");
CREATE INDEX ix_121 ON "payment_allocations" ("settlement_payment_intent_id");
CREATE INDEX ix_122 ON "financial_ledger_entries" ("workspace_id");
CREATE INDEX ix_123 ON "financial_ledger_entries" ("data_product_id");
CREATE INDEX ix_124 ON "financial_ledger_entries" ("payment_intent_id");
CREATE INDEX ix_125 ON "financial_ledger_entries" ("payment_allocation_id");
CREATE INDEX ix_126 ON "financial_ledger_entries" ("wallet_address_id");
CREATE INDEX ix_127 ON "financial_ledger_entries" ("network_id");
CREATE INDEX ix_128 ON "financial_ledger_entries" ("asset_id");
CREATE INDEX ix_129 ON "financial_ledger_entries" ("reverses_entry_id");
CREATE INDEX ix_130 ON "control_commands" ("actor_user_id");
CREATE INDEX ix_131 ON "control_commands" ("workspace_id");
CREATE INDEX ix_132 ON "control_commands" ("trace_stream_id");
CREATE INDEX ix_133 ON "planning_checkpoints" ("agent_session_id");
CREATE INDEX ix_134 ON "planning_checkpoints" ("parent_version_id");
CREATE INDEX ix_135 ON "planning_calls" ("control_command_id");
CREATE INDEX ix_136 ON "planning_calls" ("result_message_id");
CREATE INDEX ix_137 ON "run_source_contexts" ("source_snapshot_id");
CREATE INDEX ix_138 ON "compilation_records" ("workspace_id");
CREATE INDEX ix_139 ON "compilation_records" ("proposal_message_id");
CREATE INDEX ix_140 ON "compilation_records" ("data_product_version_id");
CREATE INDEX ix_141 ON "compilation_records" ("proposal_compilation_id");
CREATE INDEX ix_142 ON "api_payment_proofs" ("api_access_request_id");
CREATE INDEX ix_143 ON "api_payment_proofs" ("payment_intent_id");
CREATE INDEX ix_144 ON "users" (status, created_at);
CREATE INDEX ix_145 ON "account_wallets" (workspace_id, status);
CREATE INDEX ix_146 ON "wallet_signer_grants" (account_wallet_id, status, valid_until);
CREATE INDEX ix_147 ON "spending_policies" (workspace_id, status, period_ends_at);
CREATE INDEX ix_148 ON "budget_reservations" (spending_policy_id, status, expires_at);
CREATE INDEX ix_149 ON "wallet_balance_snapshots" (wallet_address_id, asset_id, observed_at DESC);
CREATE INDEX ix_150 ON "agent_sessions" (workspace_id, status, created_at DESC);
CREATE INDEX ix_151 ON "provider_credentials" (workspace_id, provider, status);
CREATE INDEX ix_152 ON "source_snapshots" (workspace_id, provider, source_kind, status);
CREATE INDEX ix_153 ON "source_snapshots" (provider, logical_source_id);
CREATE INDEX ix_154 ON "data_products" (workspace_id, status, updated_at DESC);
CREATE INDEX ix_155 ON "data_product_versions" (data_product_id, status, created_at DESC);
CREATE INDEX ix_156 ON "refresh_schedules" (status, next_run_at);
CREATE INDEX ix_157 ON "execution_runs" (data_product_id, status, queued_at DESC);
CREATE INDEX ix_158 ON "execution_runs" (status, queued_at);
CREATE INDEX ix_159 ON "artifacts" (workspace_id, content_hash, artifact_kind);
CREATE INDEX ix_160 ON "source_requests" (source_snapshot_id, status);
CREATE INDEX ix_161 ON "source_http_attempts" (status, sent_at);
CREATE INDEX ix_162 ON "materializations" (data_product_id, status, source_freshness_at DESC);
CREATE INDEX ix_163 ON "trace_streams" (data_product_id, created_at DESC);
CREATE INDEX ix_164 ON "usage_events" (workspace_id, metric, recorded_at);
CREATE INDEX ix_165 ON "payment_intents" (workspace_id, kind, status, created_at DESC);
CREATE INDEX ix_166 ON "control_commands" (workspace_id, status, created_at);
CREATE INDEX ix_167 ON "command_dispatches" (status, next_attempt_at);
CREATE INDEX ix_168 ON "planning_calls" (control_command_id, status);
ALTER TABLE "workspace_members" ADD CONSTRAINT ck_001 CHECK (((status <> 'revoked' OR revoked_at IS NOT NULL)) IS TRUE);
ALTER TABLE "account_wallets" ADD CONSTRAINT ck_002 CHECK (((status = 'archived') = (archived_at IS NOT NULL)) IS TRUE);
ALTER TABLE "wallet_addresses" ADD CONSTRAINT ck_003 CHECK ((control_status <> 'verified' OR (verified_at IS NOT NULL AND control_evidence_ref IS NOT NULL)) IS TRUE);
ALTER TABLE "wallet_addresses" ADD CONSTRAINT ck_004 CHECK ((NOT (can_receive OR can_spend) OR control_status = 'verified') IS TRUE);
ALTER TABLE "wallet_signer_grants" ADD CONSTRAINT ck_005 CHECK ((valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from) IS TRUE);
ALTER TABLE "wallet_signer_grants" ADD CONSTRAINT ck_006 CHECK ((status <> 'revoked' OR revoked_at IS NOT NULL) IS TRUE);
ALTER TABLE "wallet_signer_grants" ADD CONSTRAINT ck_007 CHECK ((status <> 'active' OR (consent_evidence_ref IS NOT NULL AND signer_secret_ref IS NOT NULL AND granted_at IS NOT NULL)) IS TRUE);
ALTER TABLE "spending_policies" ADD CONSTRAINT ck_008 CHECK ((period_ends_at > period_starts_at) IS TRUE);
ALTER TABLE "spending_policies" ADD CONSTRAINT ck_009 CHECK ((max_per_request_atomic > 0 AND max_per_period_atomic > 0) IS TRUE);
ALTER TABLE "spending_policies" ADD CONSTRAINT ck_010 CHECK ((max_per_request_atomic <= max_per_period_atomic) IS TRUE);
ALTER TABLE "budget_reservations" ADD CONSTRAINT ck_011 CHECK ((amount_atomic > 0) IS TRUE);
ALTER TABLE "budget_reservations" ADD CONSTRAINT ck_012 CHECK (((status = 'consumed') = (consumed_payment_intent_id IS NOT NULL)) IS TRUE);
ALTER TABLE "agent_messages" ADD CONSTRAINT ck_013 CHECK ((content_text IS NOT NULL OR content_json IS NOT NULL OR redaction_status = 'content_removed') IS TRUE);
ALTER TABLE "provider_credentials" ADD CONSTRAINT ck_014 CHECK ((status <> 'revoked' OR revoked_at IS NOT NULL) IS TRUE);
ALTER TABLE "provider_credentials" ADD CONSTRAINT ck_015 CHECK ((status <> 'active' OR validated_at IS NOT NULL) IS TRUE);
ALTER TABLE "source_snapshots" ADD CONSTRAINT ck_016 CHECK ((octet_length(schema_document) <= 5242880) IS TRUE);
ALTER TABLE "source_snapshots" ADD CONSTRAINT ck_017 CHECK ((status <> 'validated' OR validated_at IS NOT NULL) IS TRUE);
ALTER TABLE "data_product_versions" ADD CONSTRAINT ck_018 CHECK ((jsonb_typeof(specification_json) = 'object') IS TRUE);
ALTER TABLE "data_product_versions" ADD CONSTRAINT ck_019 CHECK (((specification_json->>'schemaVersion')::integer = spec_schema_version) IS TRUE);
ALTER TABLE "data_product_versions" ADD CONSTRAINT ck_020 CHECK ((output_schema_json = specification_json->'outputSchema') IS TRUE);
ALTER TABLE "data_product_versions" ADD CONSTRAINT ck_021 CHECK ((jsonb_typeof(specification_json->'dag'->'nodes') = 'array') IS TRUE);
ALTER TABLE "data_product_versions" ADD CONSTRAINT ck_022 CHECK ((jsonb_typeof(specification_json->'sources') = 'array') IS TRUE);
ALTER TABLE "data_product_versions" ADD CONSTRAINT ck_023 CHECK ((status <> 'ready' OR ready_at IS NOT NULL) IS TRUE);
ALTER TABLE "data_product_versions" ADD CONSTRAINT ck_024 CHECK ((validated_at IS NULL OR (validation_summary_json->>'passed')::boolean = true) IS TRUE);
ALTER TABLE "data_product_version_sources" ADD CONSTRAINT ck_025 CHECK (((access_mode = 'customer_api_key' AND provider_credential_id IS NOT NULL AND spending_policy_id IS NULL) OR (access_mode = 'x402' AND provider_credential_id IS NULL AND spending_policy_id IS NOT NULL)) IS TRUE);
ALTER TABLE "product_version_layouts" ADD CONSTRAINT ck_026 CHECK ((jsonb_typeof(layout_json) = 'object') IS TRUE);
ALTER TABLE "deployments" ADD CONSTRAINT ck_027 CHECK (((active_version_id IS NULL) = (active_materialization_id IS NULL)) IS TRUE);
ALTER TABLE "publication_versions" ADD CONSTRAINT ck_028 CHECK ((NOT service_fee_enabled OR (service_fee_terms_json IS NOT NULL AND accepted_by_user_id IS NOT NULL AND accepted_at IS NOT NULL)) IS TRUE);
ALTER TABLE "publication_versions" ADD CONSTRAINT ck_029 CHECK ((access_mode <> 'x402' OR (network_id IS NOT NULL AND asset_id IS NOT NULL AND price_atomic > 0 AND recipient_wallet_address_id IS NOT NULL AND payment_protocol_version = '2' AND payment_scheme = 'exact' AND max_timeout_seconds > 0 AND facilitator = 'blocky402' AND facilitator_config_ref IS NOT NULL AND facilitator_capability_hash IS NOT NULL AND facilitator_capability_json IS NOT NULL AND facilitator_capability_observed_at IS NOT NULL)) IS TRUE);
ALTER TABLE "api_credentials" ADD CONSTRAINT ck_030 CHECK ((status <> 'revoked' OR revoked_at IS NOT NULL) IS TRUE);
ALTER TABLE "node_runs" ADD CONSTRAINT ck_031 CHECK ((operator_version <> '') IS TRUE);
ALTER TABLE "node_run_artifacts" ADD CONSTRAINT ck_032 CHECK ((port_name = 'rows') IS TRUE);
ALTER TABLE "artifacts" ADD CONSTRAINT ck_033 CHECK (((storage_kind = 'inline_json' AND payload_json IS NOT NULL AND object_uri IS NULL AND byte_count <= 5242880 AND octet_length(payload_json::text) <= 5242880) OR (storage_kind = 'object_uri' AND payload_json IS NULL AND object_uri IS NOT NULL)) IS TRUE);
ALTER TABLE "source_requests" ADD CONSTRAINT ck_034 CHECK (((access_mode = 'customer_api_key' AND provider_credential_id IS NOT NULL AND credential_secret_version IS NOT NULL AND credential_fingerprint IS NOT NULL AND spending_policy_id IS NULL AND budget_reservation_id IS NULL AND payment_intent_id IS NULL) OR (access_mode = 'x402' AND spending_policy_id IS NOT NULL AND provider_credential_id IS NULL AND credential_secret_version IS NULL AND credential_fingerprint IS NULL)) IS TRUE);
ALTER TABLE "source_http_attempts" ADD CONSTRAINT ck_035 CHECK ((has_payment_authorization = (payment_authorization_hash IS NOT NULL)) IS TRUE);
ALTER TABLE "source_http_attempts" ADD CONSTRAINT ck_036 CHECK ((status <> 'payment_required' OR http_status = 402) IS TRUE);
ALTER TABLE "trace_streams" ADD CONSTRAINT ck_037 CHECK ((num_nonnulls(data_product_id, data_product_version_id, agent_session_id, execution_run_id) > 0) IS TRUE);
ALTER TABLE "api_access_requests" ADD CONSTRAINT ck_038 CHECK ((num_nonnulls(recovery_capability_hash, recovery_hash_key_version, recovery_expires_at) IN (0,3)) IS TRUE);
ALTER TABLE "api_access_requests" ADD CONSTRAINT ck_039 CHECK ((recovery_capability_hash IS NULL OR (idempotency_key IS NOT NULL AND recovery_expires_at > started_at)) IS TRUE);
ALTER TABLE "api_access_requests" ADD CONSTRAINT ck_040 CHECK ((recovery_revoked_at IS NULL OR recovery_capability_hash IS NOT NULL) IS TRUE);
ALTER TABLE "api_http_attempts" ADD CONSTRAINT ck_041 CHECK ((has_payment_authorization = (payment_authorization_hash IS NOT NULL)) IS TRUE);
ALTER TABLE "usage_events" ADD CONSTRAINT ck_042 CHECK ((num_nonnulls(data_product_id, execution_run_id, source_request_id, api_access_request_id) > 0) IS TRUE);
ALTER TABLE "payment_intents" ADD CONSTRAINT ck_043 CHECK ((amount_atomic > 0) IS TRUE);
ALTER TABLE "payment_intents" ADD CONSTRAINT ck_044 CHECK ((payment_protocol <> 'x402' OR (payment_protocol_version IS NOT NULL AND payment_scheme IS NOT NULL AND max_timeout_seconds > 0 AND requirement_hash IS NOT NULL AND selected_requirement_json IS NOT NULL)) IS TRUE);
ALTER TABLE "payment_attempts" ADD CONSTRAINT ck_045 CHECK ((provider_idempotency_key IS NULL OR request_fingerprint IS NOT NULL) IS TRUE);
ALTER TABLE "payment_settlements" ADD CONSTRAINT ck_046 CHECK ((amount_atomic > 0) IS TRUE);
ALTER TABLE "payment_settlements" ADD CONSTRAINT ck_047 CHECK ((status <> 'confirmed' OR (confirmed_at IS NOT NULL AND result_code IS NOT NULL AND num_nonnulls(network_transaction_id, network_transaction_hash) > 0 AND evidence_hash IS NOT NULL AND evidence_json IS NOT NULL)) IS TRUE);
ALTER TABLE "financial_ledger_entries" ADD CONSTRAINT ck_048 CHECK ((amount_atomic > 0) IS TRUE);
ALTER TABLE "financial_ledger_entries" ADD CONSTRAINT ck_049 CHECK (((accounting_view = 'cash_movement' AND wallet_address_id IS NOT NULL AND direction IN ('inflow','outflow')) OR (accounting_view = 'economic_allocation' AND direction = 'memo')) IS TRUE);
ALTER TABLE "control_commands" ADD CONSTRAINT ck_050 CHECK ((length(idempotency_key) BETWEEN 16 AND 128 AND idempotency_key ~ '^[ -~]+$') IS TRUE);
ALTER TABLE "control_commands" ADD CONSTRAINT ck_051 CHECK (((subject_type IS NULL) = (subject_id IS NULL)) IS TRUE);
ALTER TABLE "control_commands" ADD CONSTRAINT ck_052 CHECK (((status IN ('succeeded','failed','cancelled')) = (finished_at IS NOT NULL)) IS TRUE);
ALTER TABLE "control_commands" ADD CONSTRAINT ck_053 CHECK ((workspace_id IS NOT NULL OR trace_stream_id IS NULL) IS TRUE);
ALTER TABLE "planning_checkpoints" ADD CONSTRAINT ck_054 CHECK ((repairs_used <= repair_limit) IS TRUE);
ALTER TABLE "planning_checkpoints" ADD CONSTRAINT ck_055 CHECK ((deadline_at > created_at) IS TRUE);
-- Retain observed provider overruns rather than dropping evidence. Future reservations
-- count greatest(reserved, observed); the worker must block/escalate an overrun.
ALTER TABLE "planning_calls" ADD CONSTRAINT ck_059 CHECK ((call_kind <> 'tool' OR (reserved_input_tokens = 0 AND reserved_output_tokens = 0 AND reserved_cost_atomic = 0)) IS TRUE);
ALTER TABLE "run_source_contexts" ADD CONSTRAINT ck_060 CHECK (((window_start IS NULL) = (window_end IS NULL)) IS TRUE);
ALTER TABLE "run_source_contexts" ADD CONSTRAINT ck_061 CHECK ((window_end IS NULL OR window_end > window_start) IS TRUE);
ALTER TABLE "run_source_contexts" ADD CONSTRAINT ck_062 CHECK (((status = 'frozen') = (frozen_at IS NOT NULL)) IS TRUE);
ALTER TABLE "run_source_contexts" ADD CONSTRAINT ck_063 CHECK ((status <> 'frozen' OR requested_block_ref IS NOT NULL) IS TRUE);
ALTER TABLE "run_source_contexts" ADD CONSTRAINT ck_064 CHECK ((jsonb_typeof(base_variables_json) = 'object') IS TRUE);
ALTER TABLE "compilation_records" ADD CONSTRAINT ck_065 CHECK ((num_nonnulls(proposal_message_id, data_product_version_id) = 1) IS TRUE);
ALTER TABLE "compilation_records" ADD CONSTRAINT ck_066 CHECK ((proposal_compilation_id IS NULL OR data_product_version_id IS NOT NULL) IS TRUE);
ALTER TABLE "compilation_records" ADD CONSTRAINT ck_067 CHECK ((jsonb_typeof(provenance_json) = 'object') IS TRUE);
ALTER TABLE "compilation_records" ADD CONSTRAINT ck_068 CHECK (((provenance_json->>'schemaVersion')::integer = schema_version) IS TRUE);
ALTER TABLE "compilation_records" ADD CONSTRAINT ck_069 CHECK ((provenance_json->>'compilerVersion' = compiler_version) IS TRUE);
ALTER TABLE "compilation_records" ADD CONSTRAINT ck_070 CHECK ((provenance_json->>'templateCatalogHash' = template_catalog_hash) IS TRUE);
ALTER TABLE "compilation_records" ADD CONSTRAINT ck_071 CHECK ((provenance_json->>'expandedSpecHash' = expanded_spec_hash) IS TRUE);
ALTER TABLE "compilation_records" ADD CONSTRAINT ck_072 CHECK ((jsonb_typeof(provenance_json->'instances') = 'array') IS TRUE);
