import type { RouteDefinition } from "../contracts/route.js";
// Reserved operations mirror docs/api/products-builder.md; they never accept work or return mock success.
export const builderRoutes: readonly RouteDefinition[] = [
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/products",
    operationId: "getApiV1WorkspacesWorkspaceIdProducts",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/products",
    operationId: "postApiV1WorkspacesWorkspaceIdProducts",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/products/{productId}",
    operationId: "getApiV1WorkspacesWorkspaceIdProductsProductId",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "PATCH",
    path: "/api/v1/workspaces/{workspaceId}/products/{productId}",
    operationId: "patchApiV1WorkspacesWorkspaceIdProductsProductId",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: true,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/products/{productId}/runs",
    operationId: "getApiV1WorkspacesWorkspaceIdProductsProductIdRuns",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/products/{productId}/versions",
    operationId: "getApiV1WorkspacesWorkspaceIdProductsProductIdVersions",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/agent-sessions",
    operationId: "postApiV1WorkspacesWorkspaceIdAgentSessions",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/agent-sessions",
    operationId: "getApiV1WorkspacesWorkspaceIdAgentSessions",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/agent-sessions/{sessionId}",
    operationId: "getApiV1WorkspacesWorkspaceIdAgentSessionsSessionId",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/agent-sessions/{sessionId}/messages",
    operationId: "getApiV1WorkspacesWorkspaceIdAgentSessionsSessionIdMessages",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/agent-sessions/{sessionId}/messages",
    operationId: "postApiV1WorkspacesWorkspaceIdAgentSessionsSessionIdMessages",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/agent-sessions/{sessionId}/proposals/{messageId}/discard",
    operationId:
      "postApiV1WorkspacesWorkspaceIdAgentSessionsSessionIdProposalsMessageIdDiscard",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/agent-sessions/{sessionId}/planning/{commandId}/cancel",
    operationId:
      "postApiV1WorkspacesWorkspaceIdAgentSessionsSessionIdPlanningCommandIdCancel",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/agent-sessions/{sessionId}/proposals/{messageId}",
    operationId:
      "getApiV1WorkspacesWorkspaceIdAgentSessionsSessionIdProposalsMessageId",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/products/{productId}/versions",
    operationId: "postApiV1WorkspacesWorkspaceIdProductsProductIdVersions",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/operator-registry",
    operationId: "getApiV1OperatorRegistry",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/source-snapshots/{snapshotId}",
    operationId: "getApiV1WorkspacesWorkspaceIdSourceSnapshotsSnapshotId",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/source-snapshots/{snapshotId}/schema",
    operationId: "getApiV1WorkspacesWorkspaceIdSourceSnapshotsSnapshotIdSchema",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/products/{productId}/versions/{versionId}",
    operationId:
      "getApiV1WorkspacesWorkspaceIdProductsProductIdVersionsVersionId",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/products/{productId}/versions/{versionId}/diff",
    operationId:
      "getApiV1WorkspacesWorkspaceIdProductsProductIdVersionsVersionIdDiff",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/products/{productId}/versions/{versionId}/validate",
    operationId:
      "postApiV1WorkspacesWorkspaceIdProductsProductIdVersionsVersionIdValidate",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/products/{productId}/versions/{versionId}/layout",
    operationId:
      "getApiV1WorkspacesWorkspaceIdProductsProductIdVersionsVersionIdLayout",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "PUT",
    path: "/api/v1/workspaces/{workspaceId}/products/{productId}/versions/{versionId}/layout",
    operationId:
      "putApiV1WorkspacesWorkspaceIdProductsProductIdVersionsVersionIdLayout",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: true,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/products/{productId}/build-preflight",
    operationId:
      "postApiV1WorkspacesWorkspaceIdProductsProductIdBuildPreflight",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/products/{productId}/runs",
    operationId: "postApiV1WorkspacesWorkspaceIdProductsProductIdRuns",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/runs/{runId}",
    operationId: "getApiV1WorkspacesWorkspaceIdRunsRunId",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/runs/{runId}/cancel",
    operationId: "postApiV1WorkspacesWorkspaceIdRunsRunIdCancel",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/runs/{runId}/resume",
    operationId: "postApiV1WorkspacesWorkspaceIdRunsRunIdResume",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/runs/{runId}/attempts",
    operationId: "getApiV1WorkspacesWorkspaceIdRunsRunIdAttempts",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/runs/{runId}/nodes",
    operationId: "getApiV1WorkspacesWorkspaceIdRunsRunIdNodes",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/runs/{runId}/source-requests",
    operationId: "getApiV1WorkspacesWorkspaceIdRunsRunIdSourceRequests",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/source-requests/{sourceRequestId}",
    operationId: "getApiV1WorkspacesWorkspaceIdSourceRequestsSourceRequestId",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/runs/{runId}/output",
    operationId: "getApiV1WorkspacesWorkspaceIdRunsRunIdOutput",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/artifacts/{artifactId}",
    operationId: "getApiV1WorkspacesWorkspaceIdArtifactsArtifactId",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/artifacts/{artifactId}/content",
    operationId: "getApiV1WorkspacesWorkspaceIdArtifactsArtifactIdContent",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
];
