import type { RouteDefinition } from "../contracts/route.js";
// Route ownership mirrors docs/api/identity-wallet.md.
export const identityRoutes: readonly RouteDefinition[] = [
  {
    method: "GET",
    path: "/api/v1/app-config",
    operationId: "getApiV1AppConfig",
    audience: "public",
    implementation: "app-config",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/bootstrap",
    operationId: "postApiV1Bootstrap",
    audience: "creator",
    implementation: "bootstrap",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/me",
    operationId: "getApiV1Me",
    audience: "creator",
    implementation: "me",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/overview",
    operationId: "getApiV1WorkspacesWorkspaceIdOverview",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/wallet-access",
    operationId: "getApiV1WorkspacesWorkspaceIdWalletAccess",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/wallets",
    operationId: "getApiV1WorkspacesWorkspaceIdWallets",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/wallets/{walletId}",
    operationId: "getApiV1WorkspacesWorkspaceIdWalletsWalletId",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/wallets/synchronize",
    operationId: "postApiV1WorkspacesWorkspaceIdWalletsSynchronize",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/wallets/{walletId}/refresh-balances",
    operationId: "postApiV1WorkspacesWorkspaceIdWalletsWalletIdRefreshBalances",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/wallets/{walletId}/funding-instructions",
    operationId:
      "getApiV1WorkspacesWorkspaceIdWalletsWalletIdFundingInstructions",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/graph-credentials",
    operationId: "getApiV1WorkspacesWorkspaceIdGraphCredentials",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/graph-credentials",
    operationId: "postApiV1WorkspacesWorkspaceIdGraphCredentials",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/graph-credentials/{credentialId}",
    operationId: "getApiV1WorkspacesWorkspaceIdGraphCredentialsCredentialId",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/graph-credentials/{credentialId}/validate",
    operationId:
      "postApiV1WorkspacesWorkspaceIdGraphCredentialsCredentialIdValidate",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: true,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/graph-credentials/{credentialId}/rotate",
    operationId:
      "postApiV1WorkspacesWorkspaceIdGraphCredentialsCredentialIdRotate",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: true,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/graph-credentials/{credentialId}/revoke",
    operationId:
      "postApiV1WorkspacesWorkspaceIdGraphCredentialsCredentialIdRevoke",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: true,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/graph-delegation-config",
    operationId: "getApiV1WorkspacesWorkspaceIdGraphDelegationConfig",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/wallets/{walletId}/synchronize-grants",
    operationId:
      "postApiV1WorkspacesWorkspaceIdWalletsWalletIdSynchronizeGrants",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/signer-grants/{grantId}",
    operationId: "getApiV1WorkspacesWorkspaceIdSignerGrantsGrantId",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/signer-grants/{grantId}/block",
    operationId: "postApiV1WorkspacesWorkspaceIdSignerGrantsGrantIdBlock",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/spending-policies",
    operationId: "getApiV1WorkspacesWorkspaceIdSpendingPolicies",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/spending-policies",
    operationId: "postApiV1WorkspacesWorkspaceIdSpendingPolicies",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/spending-policies/{policyId}",
    operationId: "getApiV1WorkspacesWorkspaceIdSpendingPoliciesPolicyId",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/spending-policies/{policyId}/activate",
    operationId:
      "postApiV1WorkspacesWorkspaceIdSpendingPoliciesPolicyIdActivate",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: true,
  },
  {
    method: "PATCH",
    path: "/api/v1/workspaces/{workspaceId}/spending-policies/{policyId}",
    operationId: "patchApiV1WorkspacesWorkspaceIdSpendingPoliciesPolicyId",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: true,
  },
  {
    method: "GET",
    path: "/api/v1/workspaces/{workspaceId}/recipient-capabilities",
    operationId: "getApiV1WorkspacesWorkspaceIdRecipientCapabilities",
    audience: "creator",
    implementation: "reserved",
    idempotency: false,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/wallets/{walletId}/resolve-hedera",
    operationId: "postApiV1WorkspacesWorkspaceIdWalletsWalletIdResolveHedera",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
  {
    method: "POST",
    path: "/api/v1/workspaces/{workspaceId}/wallet-addresses/{addressId}/refresh-capabilities",
    operationId:
      "postApiV1WorkspacesWorkspaceIdWalletAddressesAddressIdRefreshCapabilities",
    audience: "creator",
    implementation: "reserved",
    idempotency: true,
    ifMatch: false,
  },
];
